### ISSUE TITLE
Implement Character View Controller

### ISSUE THREAD

**Issue by whuang8** [Three-Eyed-Raven/ThreeEyedRaven#3]
## Task
**Description**: Create the view controller for the characters view and implement a custom character tableview cell

- [x] Create characters view controller on storyboard
- [x] Create characters view controller class
- [x] Create table view prototype cell on storyboard
- [x] Create custom table view cell class 
- [x] Conform characters view controller class to UITableViewDelegate and UITableViewDataSource
