### ISSUE TITLE
Implement House View Controller

### ISSUE THREAD

**Issue by FionaBronwen** [Three-Eyed-Raven/ThreeEyedRaven#7]
## Task

**Description:** Create the view controller for the houses view and implement a custom house collection view cell

- [x] Create houses view controller on storyboard
- [x]  Create houses view controller class
- [x] Create collection view prototype cell on storyboard
- [x] Create custom collection view cell class
- [x] Conform houses view controller class to UICollectionViewDelegate and UICollectionViewDataSource
